-- +goose Up
CREATE SCHEMA partman;
CREATE EXTENSION pg_partman WITH SCHEMA partman;
CREATE EXTENSION pg_cron;

CREATE TABLE short_url_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    short_code TEXT NOT NULL
        REFERENCES short_urls(short_code)
        ON DELETE CASCADE,
    visited_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, short_code, visited_at)
) PARTITION BY RANGE (visited_at);

SELECT partman.create_partition(
    p_parent_table := 'public.short_url_visits',
    p_control := 'visited_at',
    p_interval := '1 day',
    p_type := 'range',
    p_premake := 7,
    p_default_table := true,
    p_automatic_maintenance := 'on',
    p_jobmon := false
);

SELECT cron.schedule(
    'short-url-visits-partition-maintenance',
    '0 * * * *',
    'CALL partman.run_maintenance_proc()'
);

-- +goose Down
SELECT cron.unschedule('short-url-visits-partition-maintenance');
SELECT partman.config_cleanup('public.short_url_visits');
DROP TABLE IF EXISTS short_url_visits;
DROP EXTENSION pg_cron;
DROP EXTENSION pg_partman;
DROP SCHEMA partman;
