-- +goose Up
CREATE TABLE IF NOT EXISTS short_urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_url TEXT NOT NULL,
    short_code TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- +goose Down
DROP TABLE IF EXISTS short_urls;
