repos:
  - repo: local
    hooks:
      - id: testifylint
        name: testifylint
        entry: testifylint ./...
        language: system
        files: ^backend/.*_test\.go$
        pass_filenames: false
