// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/url"

	"github.com/mumtozvalijonov/url-shortener/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockShortenerService creates a new instance of MockShortenerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortenerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortenerService {
	mock := &MockShortenerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortenerService is an autogenerated mock type for the ShortenerService type
type MockShortenerService struct {
	mock.Mock
}

type MockShortenerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortenerService) EXPECT() *MockShortenerService_Expecter {
	return &MockShortenerService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockShortenerService
func (_mock *MockShortenerService) Delete(ctx context.Context, code string) error {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShortenerService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockShortenerService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockShortenerService_Expecter) Delete(ctx any, code any) *MockShortenerService_Delete_Call {
	return &MockShortenerService_Delete_Call{Call: _e.mock.On("Delete", ctx, code)}
}

func (_c *MockShortenerService_Delete_Call) Run(run func(ctx context.Context, code string)) *MockShortenerService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortenerService_Delete_Call) Return(err error) *MockShortenerService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShortenerService_Delete_Call) RunAndReturn(run func(ctx context.Context, code string) error) *MockShortenerService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatistics provides a mock function for the type MockShortenerService
func (_mock *MockShortenerService) GetStatistics(ctx context.Context, code string) (domain.ShortURLStatistics, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetStatistics")
	}

	var r0 domain.ShortURLStatistics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.ShortURLStatistics, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.ShortURLStatistics); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Get(0).(domain.ShortURLStatistics)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortenerService_GetStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatistics'
type MockShortenerService_GetStatistics_Call struct {
	*mock.Call
}

// GetStatistics is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockShortenerService_Expecter) GetStatistics(ctx any, code any) *MockShortenerService_GetStatistics_Call {
	return &MockShortenerService_GetStatistics_Call{Call: _e.mock.On("GetStatistics", ctx, code)}
}

func (_c *MockShortenerService_GetStatistics_Call) Run(run func(ctx context.Context, code string)) *MockShortenerService_GetStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortenerService_GetStatistics_Call) Return(shortURLStatistics domain.ShortURLStatistics, err error) *MockShortenerService_GetStatistics_Call {
	_c.Call.Return(shortURLStatistics, err)
	return _c
}

func (_c *MockShortenerService_GetStatistics_Call) RunAndReturn(run func(ctx context.Context, code string) (domain.ShortURLStatistics, error)) *MockShortenerService_GetStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function for the type MockShortenerService
func (_mock *MockShortenerService) Retrieve(ctx context.Context, code string) (domain.ShortURL, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 domain.ShortURL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.ShortURL, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.ShortURL); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Get(0).(domain.ShortURL)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortenerService_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type MockShortenerService_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockShortenerService_Expecter) Retrieve(ctx any, code any) *MockShortenerService_Retrieve_Call {
	return &MockShortenerService_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx, code)}
}

func (_c *MockShortenerService_Retrieve_Call) Run(run func(ctx context.Context, code string)) *MockShortenerService_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortenerService_Retrieve_Call) Return(shortURL domain.ShortURL, err error) *MockShortenerService_Retrieve_Call {
	_c.Call.Return(shortURL, err)
	return _c
}

func (_c *MockShortenerService_Retrieve_Call) RunAndReturn(run func(ctx context.Context, code string) (domain.ShortURL, error)) *MockShortenerService_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// Shorten provides a mock function for the type MockShortenerService
func (_mock *MockShortenerService) Shorten(ctx context.Context, url1 url.URL) (domain.ShortURL, error) {
	ret := _mock.Called(ctx, url1)

	if len(ret) == 0 {
		panic("no return value specified for Shorten")
	}

	var r0 domain.ShortURL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, url.URL) (domain.ShortURL, error)); ok {
		return returnFunc(ctx, url1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, url.URL) domain.ShortURL); ok {
		r0 = returnFunc(ctx, url1)
	} else {
		r0 = ret.Get(0).(domain.ShortURL)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, url.URL) error); ok {
		r1 = returnFunc(ctx, url1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortenerService_Shorten_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shorten'
type MockShortenerService_Shorten_Call struct {
	*mock.Call
}

// Shorten is a helper method to define mock.On call
//   - ctx context.Context
//   - url1 url.URL
func (_e *MockShortenerService_Expecter) Shorten(ctx any, url1 any) *MockShortenerService_Shorten_Call {
	return &MockShortenerService_Shorten_Call{Call: _e.mock.On("Shorten", ctx, url1)}
}

func (_c *MockShortenerService_Shorten_Call) Run(run func(ctx context.Context, url1 url.URL)) *MockShortenerService_Shorten_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 url.URL
		if args[1] != nil {
			arg1 = args[1].(url.URL)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortenerService_Shorten_Call) Return(shortURL domain.ShortURL, err error) *MockShortenerService_Shorten_Call {
	_c.Call.Return(shortURL, err)
	return _c
}

func (_c *MockShortenerService_Shorten_Call) RunAndReturn(run func(ctx context.Context, url1 url.URL) (domain.ShortURL, error)) *MockShortenerService_Shorten_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockShortenerService
func (_mock *MockShortenerService) Update(ctx context.Context, code string, url1 url.URL) (domain.ShortURL, error) {
	ret := _mock.Called(ctx, code, url1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.ShortURL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, url.URL) (domain.ShortURL, error)); ok {
		return returnFunc(ctx, code, url1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, url.URL) domain.ShortURL); ok {
		r0 = returnFunc(ctx, code, url1)
	} else {
		r0 = ret.Get(0).(domain.ShortURL)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, url.URL) error); ok {
		r1 = returnFunc(ctx, code, url1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortenerService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockShortenerService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - url1 url.URL
func (_e *MockShortenerService_Expecter) Update(ctx any, code any, url1 any) *MockShortenerService_Update_Call {
	return &MockShortenerService_Update_Call{Call: _e.mock.On("Update", ctx, code, url1)}
}

func (_c *MockShortenerService_Update_Call) Run(run func(ctx context.Context, code string, url1 url.URL)) *MockShortenerService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 url.URL
		if args[2] != nil {
			arg2 = args[2].(url.URL)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShortenerService_Update_Call) Return(shortURL domain.ShortURL, err error) *MockShortenerService_Update_Call {
	_c.Call.Return(shortURL, err)
	return _c
}

func (_c *MockShortenerService_Update_Call) RunAndReturn(run func(ctx context.Context, code string, url1 url.URL) (domain.ShortURL, error)) *MockShortenerService_Update_Call {
	_c.Call.Return(run)
	return _c
}
