// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mumtozvalijonov/url-shortener/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockShortURLVisitRepository creates a new instance of MockShortURLVisitRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortURLVisitRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortURLVisitRepository {
	mock := &MockShortURLVisitRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortURLVisitRepository is an autogenerated mock type for the ShortURLVisitRepository type
type MockShortURLVisitRepository struct {
	mock.Mock
}

type MockShortURLVisitRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortURLVisitRepository) EXPECT() *MockShortURLVisitRepository_Expecter {
	return &MockShortURLVisitRepository_Expecter{mock: &_m.Mock}
}

// InsertVisits provides a mock function for the type MockShortURLVisitRepository
func (_mock *MockShortURLVisitRepository) InsertVisits(ctx context.Context, visits []domain.ShortURLVisited) error {
	ret := _mock.Called(ctx, visits)

	if len(ret) == 0 {
		panic("no return value specified for InsertVisits")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.ShortURLVisited) error); ok {
		r0 = returnFunc(ctx, visits)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShortURLVisitRepository_InsertVisits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertVisits'
type MockShortURLVisitRepository_InsertVisits_Call struct {
	*mock.Call
}

// InsertVisits is a helper method to define mock.On call
//   - ctx context.Context
//   - visits []domain.ShortURLVisited
func (_e *MockShortURLVisitRepository_Expecter) InsertVisits(ctx any, visits any) *MockShortURLVisitRepository_InsertVisits_Call {
	return &MockShortURLVisitRepository_InsertVisits_Call{Call: _e.mock.On("InsertVisits", ctx, visits)}
}

func (_c *MockShortURLVisitRepository_InsertVisits_Call) Run(run func(ctx context.Context, visits []domain.ShortURLVisited)) *MockShortURLVisitRepository_InsertVisits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.ShortURLVisited
		if args[1] != nil {
			arg1 = args[1].([]domain.ShortURLVisited)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortURLVisitRepository_InsertVisits_Call) Return(err error) *MockShortURLVisitRepository_InsertVisits_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShortURLVisitRepository_InsertVisits_Call) RunAndReturn(run func(ctx context.Context, visits []domain.ShortURLVisited) error) *MockShortURLVisitRepository_InsertVisits_Call {
	_c.Call.Return(run)
	return _c
}
